### ISSUE TITLE
Refactor components to be pure functions instead of classes unless 100% necessary for it to be a class

### ISSUE THREAD

**Issue by brentguistwite** [RowdyRuffBoysINC/RRB-client#78]

**Comment by jeffconnelly** [comment]
For reference: 

![image](https://user-images.githubusercontent.com/22281700/38260676-808c235c-3725-11e8-8999-92f8d0789ccd.png)

**Comment by Alderr** [comment]
Went ahead and converting all components into functions using what Jeff sent as a basis.
