### ISSUE TITLE
Standardize naming for components for consistency. Either camelCase or PascalCase but make sure all file names are consistent across entire project.

### ISSUE THREAD

**Issue by brentguistwite** [RowdyRuffBoysINC/RRB-client#85]

**Comment by jeffconnelly** [comment]
Airbnb recommends PascalCase for filesnames:

> Filename: Use PascalCase for filenames. E.g., ReservationCard.jsx.

https://github.com/airbnb/javascript/tree/master/react#naming

We could just do that for consistency sake.
